config/routes.rb
Rails.application.routes.draw do

  root 'subscribers#new'
  resources :subscribers
  get 'admin' => 'admin/dashboard#index'
  devise_for :admins

  namespace :admin do
    resource :dashboard, only: [:index]
    get 'show_subscribers' => 'dashboard#show_subscribers'
    resources :prizes, only: [:show, :new, :create, :edit, :update, :destroy]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
# == Schema Information
#
# Table name: conditions
#
#  id         :integer          not null, primary key
#  type       :string
#  data       :hstore
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Condition < ApplicationRecord
end

app/models/multiples_condition.rb
# == Schema Information
#
# Table name: conditions
#
#  id         :integer          not null, primary key
#  type       :string
#  data       :hstore
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MultiplesCondition < Condition



end

app/models/numbers_list_condition.rb
# == Schema Information
#
# Table name: conditions
#
#  id         :integer          not null, primary key
#  type       :string
#  data       :hstore
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class NumbersListCondition < Condition


end

app/models/prize.rb
# == Schema Information
#
# Table name: prizes
#
#  id           :integer          not null, primary key
#  name         :string
#  string       :string
#  description  :text
#  amount       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  condition_id :integer


class Prize < ApplicationRecord
  belongs_to :condition
  validates :name, :description, :amount, presence: true
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subscriber < ApplicationRecord
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  before_action :authenticate_admin!
  layout 'admin'

  def index
     @prizes = Prize.all
  end

  def show_subscribers
    @subscribers = Subscriber.all
  end

end

app/controllers/admin/prizes_controller.rb
class Admin::PrizesController < ApplicationController

layout 'admin'

  def new
    @prize = Prize.new
  end

  def create
    @prize = Prize.new(prize_params)
    if @prize.save
      flash[:success] = "El premio ha sido creado con éxito."
      redirect_to admin_path
    else
      render :new
    end
  end

  def show
    @prize = Prize.find(params[:id])
  end

  def edit
    @prize = Prize.find(params[:id])
  end

  def update
    @prize = Prize.find(params[:id])
    if @prize.update(prize_params)
      flash[:success] = "El premio fue editado con éxito."
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    Prize.find(params[:id]).destroy
    flash[:success] = "El premio fue eliminado con éxito."
    redirect_to admin_path
  end

private

  def set_prize
    @prize = Prize.find(params[:id])
  end

  def prize_params
    params.require(:prize).permit(:name, :description, :amount)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout

   private

   def layout
     if devise_controller? && devise_mapping.name == :admin
       "admin"
     else
       "application"
     end
   end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController


  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:success] = "Se ha subscrito con éxito"
      redirect_to root_path
    else
      render :index
    end
  end

private

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/prizes_helper.rb
module Admin::PrizesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subcribers_helper.rb
module SubcribersHelper
end

app/views/admin/dashboard/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center"> <strong>Listado de Premios y Disponibilidad</strong></div>

    <!-- Table -->
  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @prizes.each do |prize| %>
      <tr>
        <td><%= link_to prize.name, admin_prize_path(prize)  %></td>
        <td><%= prize.description %></td>
        <td>
          <%= prize.amount %>
        </td>
      </tr>
    <% end %>

  </tbody>
  </table>
</div>

app/views/admin/dashboard/show_subscribers.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center"> <strong>Suscriptores</strong></div>
    <!-- Table -->
  <table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Fecha y hora de inscripción</th>
    </tr>
  </thead>
  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/admin/prizes/_form.html.erb
<%= form_for @prize, url: url do |f| %>
  <% if @prize.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@prize.errors.count, "error") %> prohibited this prize from being saved:</h2>
    <ul>
      <% @prize.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, class:"form-control"  %>
  </div>
  <div class="from-group">
    <%= f.submit title, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/prizes/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Editar Premio</h1>
        </div>
        <div class="panel-body">
         <%= render 'form', url: admin_prize_path, title: "Editar"%>
       </div>
        <div class="panel-footer">
          <%= link_to 'Ver', admin_prize_path(@prize), class: "btn btn-default" %>
          <%= link_to 'Regresar', admin_path, class: "btn btn-default" %>
        </div>
    </div>
  </div>
</div>

app/views/admin/prizes/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Nuevo Premio</h1>
        </div>
        <div class="panel-body">
         <%= render 'form', url: admin_prizes_path, title: "Crear" %>
       </div>
        <div class="panel-footer">
          <%= link_to 'Regresar', admin_path, class: "btn btn-default" %>
        </div>
    </div>
  </div>
</div>

app/views/admin/prizes/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <p id="notice"><%= notice %></p>
        <div class="panel-heading">
        <p>
          <strong>Name:</strong>
          <%= @prize.name %>
        </p>
        </div>
        <div class="panel-body">
        <p>
          <strong>Description:</strong>
          <%= @prize.description %>
        </p>
        <p>
          <strong>Amount:</strong>
          <%= @prize.amount %>
        </p>
       </div>

        <div class="panel-footer center-block">
          <%= link_to 'Editar', edit_admin_prize_path(@prize), class: "btn btn-default" %>
          <%= link_to 'Eliminar', admin_prize_path(@prize), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          <%= link_to 'Regresar', admin_path, class: "btn btn-default"%>
        </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda Liftit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-brand">
      <%= link_to 'Dashboard Tienda Liftit', admin_path %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Suscriptores', admin_show_subscribers_path %></li>
        <li><%= link_to 'Nuevo Premio', new_admin_prize_path  %></li>
        <li><%= link_to 'Editar cuenta', edit_admin_registration_path  %></li>
        <li><%= link_to 'Salir', destroy_admin_session_path, method: :delete %></li>
      </ul>
  </div>
</nav>

<div class="container">
  <% flash.each do |msg_type, msg| %>
    <%= content_tag :div, msg, class: 'alert alert-info' %>
  <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiftitStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag :div, msg, class: 'alert alert-info text-center' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-md-8 col-md-offset-2 text-center">

      <div class="row">
        <h1>Liftit store</h1>
        <h4> <strong>Suscribete y mantente actualizado de todos nuestros nuevos productos, ademas constatemente estamos regalando premios a nuestros suscriptores</strong></h4>

      </div>

      <div class="row">
        <%= form_for @subscriber  do |f| %>
          <div class="form-horizontal">
            <div class="form-group">
              <%= f.text_field :email, placeholder: "Email", class:"form-control text-center" %>
            </div>

            <div class="form-group">
              <%= f.submit "Suscribirse", class: "btn btn-primary form-control text-center" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>


  </div>
</div>

app/views/subscribers/new.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-md-8 col-md-offset-2 text-center">

      <div class="row">
        <h1>Liftit store</h1>
        <h4> <strong>Suscribete y mantente actualizado de todos nuestros nuevos productos, ademas constatemente estamos regalando premios a nuestros suscriptores</strong></h4>

      </div>

      <div class="row">
        <%= form_for @subscriber do |f| %>
          <div class="form-horizontal">
            <div class="form-group">
              <%= f.text_field :email, placeholder: "Email", class:"form-control text-center" %>
            </div>

            <div class="form-group">
              <%= f.submit "Suscribirse", class: "btn btn-primary form-control text-center" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>


  </div>
</div>